"""The following is a Numba normalized AST representation of moan.py.
It was copied from moan.ast.py, and had non-normalized parts
re-written by hand.

It is more instructive to look at a graphical diff of the two files,
than separately read each in their entirety.  For example:

$ tkdiff moan.ast.py moan.nast.py
"""
moan_nast_tuple = (
 'Module',
 {'body': [
  ('Import',
   {'names': [('alias', {'asname': None, 'name': 'math'}, {})]},
   {'col_offset': 0, 'lineno': 2}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [('arg',
                        {'annotation': None, 'arg': 'invec'},
                        {})],
              'defaults': [],
              'kw_defaults': [],
              'kwarg': None,
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': None,
              'varargannotation': None},
             {}),
    'body': [('Return',
              {'value': ('BinOp',
                         {'left': ('BinOp',
                                   {'left': ('Name',
                                             {'ctx': ('Load',
                                                      {},
                                                      {}),
                                              'id': 'invec'},
                                             {'col_offset': 11,
                                              'lineno': 5}),
                                    'op': ('Mult', {}, {}),
                                    'right': ('Num',
                                              {'n': 2},
                                              {'col_offset': 19,
                                               'lineno': 5})},
                                   {'col_offset': 11,
                                    'lineno': 5}),
                          'op': ('Add', {}, {}),
                          'right': ('Num',
                                    {'n': 1},
                                    {'col_offset': 23,
                                     'lineno': 5})},
                         {'col_offset': 11, 'lineno': 5})},
              {'col_offset': 4, 'lineno': 5})],
    'decorator_list': [],
    'name': 'kernel',
    'returns': None},
   {'col_offset': 0, 'lineno': 4}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [('arg',
                        {'annotation': None, 'arg': 'it'},
                        {})],
              'defaults': [],
              'kw_defaults': [],
              'kwarg': None,
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': None,
              'varargannotation': None},
             {}),
    'body': [('For',
              {'body': [('Expr',
                         {'value': ('Yield',
                                    {'value': ('Call',
                                               {'args': [('Name',
                                                          {'ctx': ('Load',
                                                                   {},
                                                                   {}),
                                                           'id': 'other'},
                                                          {'col_offset': 21,
                                                           'lineno': 9})],
                                                'func': ('Name',
                                                         {'ctx': ('Load',
                                                                  {},
                                                                  {}),
                                                          'id': 'kernel'},
                                                         {'col_offset': 14,
                                                          'lineno': 9}),
                                                'keywords': [],
                                                'kwargs': None,
                                                'starargs': None},
                                               {'col_offset': 14,
                                                'lineno': 9})},
                                    {'col_offset': 8,
                                     'lineno': 9})},
                         {'col_offset': 8, 'lineno': 9})],
               'iter': ('Name',
                        {'ctx': ('Load', {}, {}), 'id': 'it'},
                        {'col_offset': 17, 'lineno': 8}),
               'orelse': [],
               'target': ('Name',
                          {'ctx': ('Store', {}, {}),
                           'id': 'other'},
                          {'col_offset': 8, 'lineno': 8})},
              {'col_offset': 4, 'lineno': 8})],
    'decorator_list': [],
    'name': 'gen_test',
    'returns': None},
   {'col_offset': 0, 'lineno': 7}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [('arg',
                        {'annotation': None, 'arg': 'foo'},
                        {})],
              'defaults': [],
              'kw_defaults': [],
              'kwarg': None,
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': None,
              'varargannotation': None},
             {}),
    'body': [('AugAssign',
              {'op': ('Add', {}, {}),
               'target': ('Name',
                          {'ctx': ('Store', {}, {}),
                           'id': 'foo'},
                          {'col_offset': 4, 'lineno': 12}),
               'value': ('Num',
                         {'n': 3},
                         {'col_offset': 11, 'lineno': 12})},
              {'col_offset': 4, 'lineno': 12}),
             ('FunctionDef',
              {'args': ('arguments',
                        {'args': [('arg',
                                   {'annotation': None,
                                    'arg': 'baz'},
                                   {})],
                         'defaults': [],
                         'kw_defaults': [],
                         'kwarg': None,
                         'kwargannotation': None,
                         'kwonlyargs': [],
                         'vararg': None,
                         'varargannotation': None},
                        {}),
               'body': [('Return',
                         {'value': ('BinOp',
                                    {'left': ('Name',
                                              {'ctx': ('Load',
                                                       {},
                                                       {}),
                                               'id': 'foo'},
                                              {'col_offset': 15,
                                               'lineno': 14}),
                                     'op': ('Add',
                                            {},
                                            {}),
                                     'right': ('Call',
                                               {'args': [('Name',
                                                          {'ctx': ('Load',
                                                                   {},
                                                                   {}),
                                                           'id': 'baz'},
                                                          {'col_offset': 52,
                                                           'lineno': 14})],
                                                'func': ('Lambda',
                                                         {'args': ('arguments',
                                                                   {'args': [('arg',
                                                                              {'annotation': None,
                                                                               'arg': 'x'},
                                                                              {})],
                                                                    'defaults': [],
                                                                    'kw_defaults': [],
                                                                    'kwarg': None,
                                                                    'kwargannotation': None,
                                                                    'kwonlyargs': [],
                                                                    'vararg': None,
                                                                    'varargannotation': None},
                                                                   {}),
                                                          'body': ('BinOp',
                                                                   {'left': ('Name',
                                                                             {'ctx': ('Load',
                                                                                      {},
                                                                                      {}),
                                                                              'id': 'x'},
                                                                             {'col_offset': 32,
                                                                              'lineno': 14}),
                                                                    'op': ('Sub',
                                                                           {},
                                                                           {}),
                                                                    'right': ('BinOp',
                                                                              {'left': ('Name',
                                                                                        {'ctx': ('Load',
                                                                                                 {},
                                                                                                 {}),
                                                                                         'id': 'global_z'},
                                                                                        {'col_offset': 36,
                                                                                         'lineno': 14}),
                                                                               'op': ('Mult',
                                                                                      {},
                                                                                      {}),
                                                                               'right': ('Name',
                                                                                         {'ctx': ('Load',
                                                                                                  {},
                                                                                                  {}),
                                                                                          'id': 'foo'},
                                                                                         {'col_offset': 47,
                                                                                          'lineno': 14})},
                                                                              {'col_offset': 36,
                                                                               'lineno': 14})},
                                                                   {'col_offset': 32,
                                                                    'lineno': 14})},
                                                         {'col_offset': 22,
                                                          'lineno': 14}),
                                                'keywords': [],
                                                'kwargs': None,
                                                'starargs': None},
                                               {'col_offset': 22,
                                                'lineno': 14})},
                                    {'col_offset': 15,
                                     'lineno': 14})},
                         {'col_offset': 8, 'lineno': 14})],
               'decorator_list': [],
               'name': 'bar',
               'returns': None},
              {'col_offset': 4, 'lineno': 13}),
             ('AugAssign',
              {'op': ('Add', {}, {}),
               'target': ('Name',
                          {'ctx': ('Store', {}, {}),
                           'id': 'foo'},
                          {'col_offset': 4, 'lineno': 15}),
               'value': ('Num',
                         {'n': 2},
                         {'col_offset': 11, 'lineno': 15})},
              {'col_offset': 4, 'lineno': 15}),
             ('Return',
              {'value': ('Name',
                         {'ctx': ('Load', {}, {}),
                          'id': 'bar'},
                         {'col_offset': 11, 'lineno': 16})},
              {'col_offset': 4, 'lineno': 16})],
    'decorator_list': [],
    'name': 'closure_test',
    'returns': None},
   {'col_offset': 0, 'lineno': 11}),
  # ______________________________________________________________________
  ('Assign',
   {'target': ('Name',
               {'ctx': ('Store', {}, {}), 'id': 'global_z'},
               {'col_offset': 0, 'lineno': 18}),
    'value': ('Num',
              {'n': 98.6},
              {'col_offset': 11, 'lineno': 18})},
   {'col_offset': 0, 'lineno': 18}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [('arg',
                        {'annotation': None, 'arg': 'adj'},
                        {})],
              'defaults': [],
              'kw_defaults': [],
              'kwarg': None,
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': None,
              'varargannotation': None},
             {}),
    'body': [('Global',
              {'name': 'global_z'},
              {'col_offset': 4, 'lineno': 21}),
             ('AugAssign',
              {'op': ('Add', {}, {}),
               'target': ('Name',
                          {'ctx': ('Store', {}, {}),
                           'id': 'global_z'},
                          {'col_offset': 4, 'lineno': 22}),
               'value': ('Name',
                         {'ctx': ('Load', {}, {}),
                          'id': 'adj'},
                         {'col_offset': 16, 'lineno': 22})},
              {'col_offset': 4, 'lineno': 22})],
    'decorator_list': [],
    'name': 'global_test',
    'returns': None},
   {'col_offset': 0, 'lineno': 20}),
  # ______________________________________________________________________
  ('ClassDef',
   {'bases': [],
    'body': [('FunctionDef',
              {'args': ('arguments',
                        {'args': [('arg',
                                   {'annotation': None,
                                    'arg': 'self'},
                                   {}),
                                  ('arg',
                                   {'annotation': None,
                                    'arg': 'x'},
                                   {}),
                                  ('arg',
                                   {'annotation': None,
                                    'arg': 'y'},
                                   {})],
                         'defaults': [],
                         'kw_defaults': [],
                         'kwarg': None,
                         'kwargannotation': None,
                         'kwonlyargs': [],
                         'vararg': None,
                         'varargannotation': None},
                        {}),
               'body': [('Assign',
                         {'target': ('Attribute',
                                     {'attr': 'x',
                                      'ctx': ('Store',
                                              {},
                                              {}),
                                      'value': ('Name',
                                                {'ctx': ('Load',
                                                         {},
                                                         {}),
                                                 'id': 'self'},
                                                {'col_offset': 8,
                                                 'lineno': 26})},
                                     {'col_offset': 8,
                                      'lineno': 26}),
                          'value': ('Name',
                                    {'ctx': ('Load',
                                             {},
                                             {}),
                                     'id': 'x'},
                                    {'col_offset': 17,
                                     'lineno': 26})},
                         {'col_offset': 8, 'lineno': 26}),
                        ('Assign',
                         {'target': ('Attribute',
                                     {'attr': 'y',
                                      'ctx': ('Store',
                                              {},
                                              {}),
                                      'value': ('Name',
                                                {'ctx': ('Load',
                                                         {},
                                                         {}),
                                                 'id': 'self'},
                                                {'col_offset': 8,
                                                 'lineno': 27})},
                                     {'col_offset': 8,
                                      'lineno': 27}),
                          'value': ('Name',
                                    {'ctx': ('Load',
                                             {},
                                             {}),
                                     'id': 'y'},
                                    {'col_offset': 17,
                                     'lineno': 27})},
                         {'col_offset': 8, 'lineno': 27}),
                        ('Assign',
                         {'target': ('Attribute',
                                     {'attr': 'z',
                                      'ctx': ('Store',
                                              {},
                                              {}),
                                      'value': ('Name',
                                                {'ctx': ('Load',
                                                         {},
                                                         {}),
                                                 'id': 'self'},
                                                {'col_offset': 8,
                                                 'lineno': 28})},
                                     {'col_offset': 8,
                                      'lineno': 28}),
                          'value': ('Name',
                                    {'ctx': ('Load',
                                             {},
                                             {}),
                                     'id': 'global_z'},
                                    {'col_offset': 17,
                                     'lineno': 28})},
                         {'col_offset': 8, 'lineno': 28})],
               'decorator_list': [],
               'name': '__init__',
               'returns': None},
              {'col_offset': 4, 'lineno': 25})],
    'decorator_list': [],
    'keywords': [],
    'kwargs': None,
    'name': 'ClassTest0',
    'starargs': None},
   {'col_offset': 0, 'lineno': 24}),
  # ______________________________________________________________________
  ('ClassDef',
   {'bases': [('Name',
               {'ctx': ('Load', {}, {}), 'id': 'object'},
               {'col_offset': 17, 'lineno': 30})],
    'body': [('FunctionDef',
              {'args': ('arguments',
                        {'args': [('arg',
                                   {'annotation': None,
                                    'arg': 'self'},
                                   {}),
                                  ('arg',
                                   {'annotation': None,
                                    'arg': 'x'},
                                   {}),
                                  ('arg',
                                   {'annotation': None,
                                    'arg': 'y'},
                                   {})],
                         'defaults': [],
                         'kw_defaults': [],
                         'kwarg': None,
                         'kwargannotation': None,
                         'kwonlyargs': [],
                         'vararg': None,
                         'varargannotation': None},
                        {}),
               'body': [('Assign',
                         {'target': ('Attribute',
                                     {'attr': 'x',
                                      'ctx': ('Store',
                                              {},
                                              {}),
                                      'value': ('Name',
                                                {'ctx': ('Load',
                                                         {},
                                                         {}),
                                                 'id': 'self'},
                                                {'col_offset': 8,
                                                 'lineno': 32})},
                                     {'col_offset': 8,
                                      'lineno': 32}),
                          'value': ('Name',
                                    {'ctx': ('Load',
                                             {},
                                             {}),
                                     'id': 'x'},
                                    {'col_offset': 17,
                                     'lineno': 32})},
                         {'col_offset': 8, 'lineno': 32}),
                        ('Assign',
                         {'target': ('Attribute',
                                     {'attr': 'y',
                                      'ctx': ('Store',
                                              {},
                                              {}),
                                      'value': ('Name',
                                                {'ctx': ('Load',
                                                         {},
                                                         {}),
                                                 'id': 'self'},
                                                {'col_offset': 8,
                                                 'lineno': 33})},
                                     {'col_offset': 8,
                                      'lineno': 33}),
                          'value': ('Name',
                                    {'ctx': ('Load',
                                             {},
                                             {}),
                                     'id': 'y'},
                                    {'col_offset': 17,
                                     'lineno': 33})},
                         {'col_offset': 8, 'lineno': 33}),
                        ('Assign',
                         {'target': ('Attribute',
                                     {'attr': 'z',
                                      'ctx': ('Store',
                                              {},
                                              {}),
                                      'value': ('Name',
                                                {'ctx': ('Load',
                                                         {},
                                                         {}),
                                                 'id': 'self'},
                                                {'col_offset': 8,
                                                 'lineno': 34})},
                                     {'col_offset': 8,
                                      'lineno': 34}),
                          'value': ('Name',
                                    {'ctx': ('Load',
                                             {},
                                             {}),
                                     'id': 'global_z'},
                                    {'col_offset': 17,
                                     'lineno': 34})},
                         {'col_offset': 8, 'lineno': 34})],
               'decorator_list': [],
               'name': '__init__',
               'returns': None},
              {'col_offset': 4, 'lineno': 31})],
    'decorator_list': [],
    'keywords': [],
    'kwargs': None,
    'name': 'ClassTest1',
    'starargs': None},
   {'col_offset': 0, 'lineno': 30}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [('arg',
                        {'annotation': None, 'arg': 'self'},
                        {})],
              'defaults': [],
              'kw_defaults': [],
              'kwarg': None,
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': None,
              'varargannotation': None},
             {}),
    'body': [('Return',
              {'value': ('Call',
                         {'args': [('BinOp',
                                    {'left': ('BinOp',
                                              {'left': ('BinOp',
                                                        {'left': ('Attribute',
                                                                  {'attr': 'x',
                                                                   'ctx': ('Load',
                                                                           {},
                                                                           {}),
                                                                   'value': ('Name',
                                                                             {'ctx': ('Load',
                                                                                      {},
                                                                                      {}),
                                                                              'id': 'self'},
                                                                             {'col_offset': 21,
                                                                              'lineno': 37})},
                                                                  {'col_offset': 21,
                                                                   'lineno': 37}),
                                                         'op': ('Pow',
                                                                {},
                                                                {}),
                                                         'right': ('Num',
                                                                   {'n': 2},
                                                                   {'col_offset': 31,
                                                                    'lineno': 37})},
                                                        {'col_offset': 21,
                                                         'lineno': 37}),
                                               'op': ('Add',
                                                      {},
                                                      {}),
                                               'right': ('BinOp',
                                                         {'left': ('Attribute',
                                                                   {'attr': 'y',
                                                                    'ctx': ('Load',
                                                                            {},
                                                                            {}),
                                                                    'value': ('Name',
                                                                              {'ctx': ('Load',
                                                                                       {},
                                                                                       {}),
                                                                               'id': 'self'},
                                                                              {'col_offset': 35,
                                                                               'lineno': 37})},
                                                                   {'col_offset': 35,
                                                                    'lineno': 37}),
                                                          'op': ('Pow',
                                                                 {},
                                                                 {}),
                                                          'right': ('Num',
                                                                    {'n': 2},
                                                                    {'col_offset': 45,
                                                                     'lineno': 37})},
                                                         {'col_offset': 35,
                                                          'lineno': 37})},
                                              {'col_offset': 21,
                                               'lineno': 37}),
                                     'op': ('Add',
                                            {},
                                            {}),
                                     'right': ('BinOp',
                                               {'left': ('Attribute',
                                                         {'attr': 'z',
                                                          'ctx': ('Load',
                                                                  {},
                                                                  {}),
                                                          'value': ('Name',
                                                                    {'ctx': ('Load',
                                                                             {},
                                                                             {}),
                                                                     'id': 'self'},
                                                                    {'col_offset': 49,
                                                                     'lineno': 37})},
                                                         {'col_offset': 49,
                                                          'lineno': 37}),
                                                'op': ('Pow',
                                                       {},
                                                       {}),
                                                'right': ('Num',
                                                          {'n': 2},
                                                          {'col_offset': 59,
                                                           'lineno': 37})},
                                               {'col_offset': 49,
                                                'lineno': 37})},
                                    {'col_offset': 47,
                                     'lineno': 37})],
                          'func': ('Attribute',
                                   {'attr': 'sqrt',
                                    'ctx': ('Load',
                                            {},
                                            {}),
                                    'value': ('Name',
                                              {'ctx': ('Load',
                                                       {},
                                                       {}),
                                               'id': 'math'},
                                              {'col_offset': 11,
                                               'lineno': 37})},
                                   {'col_offset': 11,
                                    'lineno': 37}),
                          'keywords': [],
                          'kwargs': None,
                          'starargs': None},
                         {'col_offset': 11, 'lineno': 37})},
              {'col_offset': 4, 'lineno': 37})],
    'decorator_list': [],
    'name': 'len',
    'returns': None},
   {'col_offset': 0, 'lineno': 36}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [('arg',
                        {'annotation': None, 'arg': 'inmap'},
                        {})],
              'defaults': [],
              'kw_defaults': [],
              'kwarg': None,
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': None,
              'varargannotation': None},
             {}),
    'body': [('Assign',
              {'target': ('Name',
                          {'ctx': ('Store', {}, {}),
                           'id': 'temp'},
                          {'col_offset': 4, 'lineno': 40}),
               'value': ('Call',
                         {'args': [],
                          'func': ('Name',
                                   {'ctx': ('Load',
                                            {},
                                            {}),
                                    'id': 'object'},
                                   {'col_offset': 11,
                                    'lineno': 40}),
                          'keywords': [],
                          'kwargs': None,
                          'starargs': None},
                         {'col_offset': 11, 'lineno': 40})},
              {'col_offset': 4, 'lineno': 40}),
             ('TryFinally',
              {'body': [('TryExcept',
                         {'body': [('Assign',
                                    {'target': ('Attribute',
                                                {'attr': 'thingy',
                                                 'ctx': ('Store',
                                                         {},
                                                         {}),
                                                 'value': ('Name',
                                                           {'ctx': ('Load',
                                                                    {},
                                                                    {}),
                                                            'id': 'temp'},
                                                           {'col_offset': 8,
                                                            'lineno': 42})},
                                                {'col_offset': 8,
                                                 'lineno': 42}),
                                     'value': ('Subscript',
                                               {'ctx': ('Load',
                                                        {},
                                                        {}),
                                                'slice': ('Index',
                                                          {'value': ('Str',
                                                                     {'s': 'foobar'},
                                                                     {'col_offset': 28,
                                                                      'lineno': 42})},
                                                          {}),
                                                'value': ('Name',
                                                          {'ctx': ('Load',
                                                                   {},
                                                                   {}),
                                                           'id': 'inmap'},
                                                          {'col_offset': 22,
                                                           'lineno': 42})},
                                               {'col_offset': 22,
                                                'lineno': 42})},
                                    {'col_offset': 8,
                                     'lineno': 42})],
                          'handlers': [('ExceptHandler',
                                        {'body': [('Assign',
                                                   {'target': ('Attribute',
                                                               {'attr': 'thingy',
                                                                'ctx': ('Store',
                                                                        {},
                                                                        {}),
                                                                'value': ('Name',
                                                                          {'ctx': ('Load',
                                                                                   {},
                                                                                   {}),
                                                                           'id': 'temp'},
                                                                          {'col_offset': 8,
                                                                           'lineno': 44})},
                                                               {'col_offset': 8,
                                                                'lineno': 44}),
                                                    'value': ('Name',
                                                              {'ctx': ('Load',
                                                                       {},
                                                                       {}),
                                                               'id': 'None'},
                                                              {'col_offset': 22,
                                                               'lineno': 44})},
                                                   {'col_offset': 8,
                                                    'lineno': 44})],
                                         'name': None,
                                         'type': ('Name',
                                                  {'ctx': ('Load',
                                                           {},
                                                           {}),
                                                   'id': 'KeyError'},
                                                  {'col_offset': 11,
                                                   'lineno': 43})},
                                        {'col_offset': 4,
                                         'lineno': 43})],
                          'orelse': []},
                         {'col_offset': 4, 'lineno': 41})],
               'finalbody': [('Delete',
                              {'target': ('Name',
                                           {'ctx': ('Del',
                                                    {},
                                                    {}),
                                            'id': 'temp'},
                                           {'col_offset': 12,
                                            'lineno': 46})},
                              {'col_offset': 8,
                               'lineno': 46})]},
              {'col_offset': 4, 'lineno': 41})],
    'decorator_list': [],
    'name': 'exception_test',
    'returns': None},
   {'col_offset': 0, 'lineno': 39}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [],
              'defaults': [],
              'kw_defaults': [],
              'kwarg': None,
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': None,
              'varargannotation': None},
             {}),
    'body': [('With',
              {'body': [('Assign',
                         {'target': ('Name',
                                       {'ctx': ('Store',
                                                {},
                                                {}),
                                        'id': 'data'},
                                       {'col_offset': 8,
                                        'lineno': 50}),
                          'value': ('Call',
                                    {'args': [],
                                     'func': ('Attribute',
                                              {'attr': 'read',
                                               'ctx': ('Load',
                                                       {},
                                                       {}),
                                               'value': ('Name',
                                                         {'ctx': ('Load',
                                                                  {},
                                                                  {}),
                                                          'id': 'me'},
                                                         {'col_offset': 15,
                                                          'lineno': 50})},
                                              {'col_offset': 15,
                                               'lineno': 50}),
                                     'keywords': [],
                                     'kwargs': None,
                                     'starargs': None},
                                    {'col_offset': 15,
                                     'lineno': 50})},
                         {'col_offset': 8, 'lineno': 50})],
               'context_expr': ('Call',
                                {'args': [('Str',
                                           {'s': 'moan.py'},
                                           {'col_offset': 14,
                                            'lineno': 49})],
                                 'func': ('Name',
                                          {'ctx': ('Load',
                                                   {},
                                                   {}),
                                           'id': 'open'},
                                          {'col_offset': 9,
                                           'lineno': 49}),
                                 'keywords': [],
                                 'kwargs': None,
                                 'starargs': None},
                                {'col_offset': 9,
                                 'lineno': 49}),
               'optional_vars': ('Name',
                                 {'ctx': ('Store', {}, {}),
                                  'id': 'me'},
                                 {'col_offset': 28,
                                  'lineno': 49})},
              {'col_offset': 9, 'lineno': 49}),
             ('Return',
              {'value': ('Name',
                         {'ctx': ('Load', {}, {}),
                          'id': 'data'},
                         {'col_offset': 11, 'lineno': 51})},
              {'col_offset': 4, 'lineno': 51})],
    'decorator_list': [],
    'name': 'with_test',
    'returns': None},
   {'col_offset': 0, 'lineno': 48}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [('arg',
                        {'annotation': None, 'arg': 'param0'},
                        {})],
              'defaults': [('Num',
                            {'n': 0},
                            {'col_offset': 24, 'lineno': 53})],
              'kw_defaults': [],
              'kwarg': 'kws',
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': 'args',
              'varargannotation': None},
             {}),
    'body': [('Assert',
              {'msg': None,
               'test': ('Let',
                        {'body': ('Let',
                                  {'body': ('BoolOp',
                                            {'boolop': ('And',
                                                        {},
                                                        {}),
                                             'left': ('Compare',
                                                      {'left': ('Name',
                                                                {'ctx': ('Load',
                                                                         {},
                                                                         {}),
                                                                 'id': '^t0'},
                                                                {}),
                                                       'op': ('Eq',
                                                              {},
                                                              {}),
                                                       'right': ('Name',
                                                                 {'ctx': ('Load',
                                                                          {},
                                                                          {}),
                                                                  'id': '^t1'},
                                                                 {})},
                                                      {}),
                                             'right': ('Let',
                                                       {'body': ('Compare',
                                                                 {'left': ('Name',
                                                                           {'ctx': ('Load',
                                                                                    {},
                                                                                    {}),
                                                                            'id': '^t1'},
                                                                           {}),
                                                                  'op': ('Lt',
                                                                         {},
                                                                         {}),
                                                                  'right': ('Name',
                                                                            {'ctx': ('Load',
                                                                                     {},
                                                                                     {}),
                                                                             'id': '^t2'},
                                                                            {})},
                                                                 {}),
                                                        'defn': ('Call',
                                                                 {'args': [('Name',
                                                                            {'ctx': ('Load',
                                                                                     {},
                                                                                     {}),
                                                                             'id': 'kws'},
                                                                            {'col_offset': 37,
                                                                             'lineno': 54})],
                                                                  'func': ('Name',
                                                                           {'ctx': ('Load',
                                                                                    {},
                                                                                    {}),
                                                                            'id': 'len'},
                                                                           {'col_offset': 33,
                                                                            'lineno': 54}),
                                                                  'keywords': [],
                                                                  'kwargs': None,
                                                                  'starargs': None},
                                                                 {'col_offset': 33,
                                                                  'lineno': 54}),
                                                        'target': '^t2'},
                                                       {})},
                                            {}),
                                   'defn': ('Call',
                                            {'args': [('Name',
                                                       {'ctx': ('Load',
                                                                {},
                                                                {}),
                                                        'id': 'args'},
                                                       {'col_offset': 25,
                                                        'lineno': 54})],
                                             'func': ('Name',
                                                      {'ctx': ('Load',
                                                               {},
                                                               {}),
                                                       'id': 'len'},
                                                      {'col_offset': 21,
                                                       'lineno': 54}),
                                             'keywords': [],
                                             'kwargs': None,
                                             'starargs': None},
                                            {'col_offset': 21,
                                             'lineno': 54}),
                                   'target': '^t1'},
                                  {}),
                         'defn': ('Name',
                                  {'ctx': ('Load', {}, {}),
                                   'id': 'param0'},
                                  {'col_offset': 11,
                                   'lineno': 54}),
                         'target': '^t0'},
                        {})},
              {'col_offset': 4, 'lineno': 54})],
    'decorator_list': [],
    'name': 'param_test',
    'returns': None},
   {'col_offset': 0, 'lineno': 53}),
  # ______________________________________________________________________
  ('FunctionDef',
   {'args': ('arguments',
             {'args': [],
              'defaults': [],
              'kw_defaults': [],
              'kwarg': None,
              'kwargannotation': None,
              'kwonlyargs': [],
              'vararg': None,
              'varargannotation': None},
             {}),
    'body': [('Assign',
              {'target': ('Name',
                          {'ctx': ('Store', {}, {}),
                           'id': 't0'},
                          {'col_offset': 4, 'lineno': 57}),
               'value': ('Call',
                         {'args': [('Num',
                                    {'n': 2},
                                    {'col_offset': 20,
                                     'lineno': 57}),
                                   ('Num',
                                    {'n': 3},
                                    {'col_offset': 23,
                                     'lineno': 57})],
                          'func': ('Name',
                                   {'ctx': ('Load',
                                            {},
                                            {}),
                                    'id': 'ClassTest0'},
                                   {'col_offset': 9,
                                    'lineno': 57}),
                          'keywords': [],
                          'kwargs': None,
                          'starargs': None},
                         {'col_offset': 9, 'lineno': 57})},
              {'col_offset': 4, 'lineno': 57}),
             ('Assign',
              {'target': ('Name',
                          {'ctx': ('Store', {}, {}),
                           'id': 't1'},
                          {'col_offset': 4, 'lineno': 58}),
               'value': ('Call',
                         {'args': [('Num',
                                    {'n': 2},
                                    {'col_offset': 20,
                                     'lineno': 58}),
                                   ('Num',
                                    {'n': 3},
                                    {'col_offset': 23,
                                     'lineno': 58})],
                          'func': ('Name',
                                   {'ctx': ('Load',
                                            {},
                                            {}),
                                    'id': 'ClassTest1'},
                                   {'col_offset': 9,
                                    'lineno': 58}),
                          'keywords': [],
                          'kwargs': None,
                          'starargs': None},
                         {'col_offset': 9, 'lineno': 58})},
              {'col_offset': 4, 'lineno': 58}),
             ('Assert',
              {'msg': None,
               'test': ('Compare',
                        {'right': ('Call',
                                   {'args': [('Name',
                                              {'ctx': ('Load',
                                                       {},
                                                       {}),
                                               'id': 't1'},
                                              {'col_offset': 26,
                                               'lineno': 59})],
                                    'func': ('Name',
                                             {'ctx': ('Load',
                                                      {},
                                                      {}),
                                              'id': 'len'},
                                             {'col_offset': 22,
                                              'lineno': 59}),
                                    'keywords': [],
                                    'kwargs': None,
                                    'starargs': None},
                                   {'col_offset': 22,
                                    'lineno': 59}),
                         'left': ('Call',
                                  {'args': [('Name',
                                             {'ctx': ('Load',
                                                      {},
                                                      {}),
                                              'id': 't0'},
                                             {'col_offset': 15,
                                              'lineno': 59})],
                                   'func': ('Name',
                                            {'ctx': ('Load',
                                                     {},
                                                     {}),
                                             'id': 'len'},
                                            {'col_offset': 11,
                                             'lineno': 59}),
                                   'keywords': [],
                                   'kwargs': None,
                                   'starargs': None},
                                  {'col_offset': 11,
                                   'lineno': 59}),
                         'ops': ('Eq', {}, {})},
                        {'col_offset': 11, 'lineno': 59})},
              {'col_offset': 4, 'lineno': 59}),
             ('Expr',
              {'value': ('Call',
                         {'args': [('Str',
                                    {'s': 'Passed.'},
                                    {'col_offset': 10,
                                     'lineno': 60})],
                          'func': ('Name',
                                   {'ctx': ('Load',
                                            {},
                                            {}),
                                    'id': 'print'},
                                   {'col_offset': 4,
                                    'lineno': 60}),
                          'keywords': [],
                          'kwargs': None,
                          'starargs': None},
                         {'col_offset': 4, 'lineno': 60})},
              {'col_offset': 4, 'lineno': 60})],
    'decorator_list': [],
    'name': 'main',
    'returns': None},
   {'col_offset': 0, 'lineno': 56}),
  # ______________________________________________________________________
  ('If',
   {'body': [('Expr',
              {'value': ('Call',
                         {'args': [],
                          'func': ('Name',
                                   {'ctx': ('Load',
                                            {},
                                            {}),
                                    'id': 'main'},
                                   {'col_offset': 4,
                                    'lineno': 63}),
                          'keywords': [],
                          'kwargs': None,
                          'starargs': None},
                         {'col_offset': 4, 'lineno': 63})},
              {'col_offset': 4, 'lineno': 63})],
    'orelse': [],
    'test': ('Compare',
             {'right': ('Str',
                        {'s': '__main__'},
                        {'col_offset': 15,
                         'lineno': 62}),
              'left': ('Name',
                       {'ctx': ('Load', {}, {}),
                        'id': '__name__'},
                       {'col_offset': 3, 'lineno': 62}),
              'op': ('Eq', {}, {})},
             {'col_offset': 3, 'lineno': 62})},
   {'col_offset': 0, 'lineno': 62})]},
 {})
